### ISSUE TITLE
Backlinks not working for some link titles containing Latex

### ISSUE THREAD

**Issue by StreitDa** [ylc395/joplin-plugin-note-link-system#1]
First of all, thank you very much for this plugin, it improves my UX in Joplin tremendously.
However, the backlinks do not appear in all my notes. I've only noticed this when there is Latex formatting in the link title, so I assume that this causes the issue somehow (most of the time, links containing Latex are displayed just fine).

I've attached a minimal repro case with a notebook containing two notes, one linking to the other, but no backlinks are generated.
 [I had to zip the .jex file to be able to upload it to github].

[LatexLinks.zip](https://github.com/ylc395/joplin-plugin-note-link-system/files/7747184/LatexLinks.zip)

**Comment by ylc395** [comment]
I figured out that links like `[aaa[bbb]cccc](url)` won't be captured as referrers, because JavaScript's regex expresstion is not strong enough to handle these links.

Now I use Markdown parser to capture links. This will capture all referrers, but may slow down Joplin(when referrers are too many).

Not well tested, so not released into Joplin Plugin Repository now. You can download & install manually to try it out.

[ylc395.noteLinkSystem.jpl.zip](https://github.com/ylc395/joplin-plugin-note-link-system/files/7755201/ylc395.noteLinkSystem.jpl.zip)

**Comment by StreitDa** [comment]
Thanks a lot! I should have realized that the problem are the brackets not the Latex. I tried out the new version and it mostly works fine, except that rarely, the same backlink is generated twice. I did not find a way to reliably reproduce this yet. If I figure it out, I'll let you know.

Thanks again for all the work you've put in this.

**Comment by ylc395** [comment]
release as 0.0.6
