### ISSUE TITLE
Dropdown for elements within notes does not working -- joplin 2.8.8

### ISSUE THREAD

**Issue by Fantasyfr** [ylc395/joplin-plugin-note-link-system#28]
In my joplin (version 2.8.8) the dropdown feature for headlines in other notes are not work any more.
Only in the current note the headlines are displayed.

To be precisely the dropdown list for the notes are displayed correctly only the headline feature are not working.

**Comment by ylc395** [comment]
not work for all notes or specific note?

**Comment by Fantasyfr** [comment]
mmh nevermind now it is working again... strange behavior

to answer your question this behavior was for all notes

**Comment by Fantasyfr** [comment]
i found the issue in the note was a triple dollar sign this caused this issue

**Comment by ylc395** [comment]
It seems that `$$$` will trigger Joplin's markdown editor's syntax parse error, which causes this predication failing.

https://github.com/ylc395/joplin-plugin-note-link-system/blob/00a9e9cc968b26d71c756918cabbf7e422509d70/src/driver/codeMirror/QuickLinker.ts#L211

We won't fix this because this is a joplin issue.
